# Tuple, Set, Dictionary

## Review of last week's course

In [ ]:
# Given the list 'l', which is consisted of 10 numbers
# count the number of elements in 'l' that are smaller than 5 using the given variable 'count'
# 'count' is initialized to 0
# You can use any techniques we have discussed -- for loop, while loop, or list comprehension.
# TODO: Make the cell print 'True'

l = [12, 3, 4, 9, 8, 100, 32, 1, 90, 2]
count = 0

### YOUR CODE HERE ###
# for val in l:
#   if val < 5:
# #     count += 1
# for i in range(len(l)):
#   if l[i] < 5:
#     count += 1

# index = 0
# while index < len(l):
#   if l[index] < 5:
#     count += 1
#   index += 1


### END OF CODE ###

# Do not modify below!
print(count == 4)

True

## Tuple

**Tuple**, just like list, is a collection of objects. But, unlike list, it is **immutable**. It means that we cannot change, add, or delete the value inside after once defined.

In [ ]:
# This is an example of using list

iphone_list = ['i', 'p', 'h', 'o', 'n', 'e']
iphone_list.append('15')
iphone_list[0] = 'I'
print(iphone_list)

['I', 'p', 'h', 'o', 'n', 'e', '15']

In [ ]:
# This is the same example as above but we used tuple instead of list
iphone_tuple = ('i', 'p', 'h', 'o', 'n', 'e')
iphone_tuple.append('15')

AttributeError: ignored

In [ ]:
# So...would this work?
iphone_tuple[0] = 'I'

TypeError: ignored

Other than this difference, tuple shares major features with list

In [ ]:
# We can use the len() function
print("The length of iphone_tuple is", len(iphone_tuple))

# We can use index to search items
print("The third element of iphone_tuple is", iphone_tuple[2])

# That includes slicing
print("All odd-indexed elements of iphone_tuple are", iphone_tuple[1::2])

# We can mix different data types
mixed_tuple = ('iphone15', 799, True)

# Can use loop
name = ""
for i in iphone_tuple:
    name += i
print(name)

# Can use if statement
if 'p' in iphone_tuple:
    print("There is p")

# Wait...can we have one element in a tuple?
bad_one_tuple = ('iphone15')
print(type(bad_one_tuple))

# We need to put ',' at the end to make a tuple with one element
good_one_tuple = ('iphone15',)
print(type(good_one_tuple))

The length of iphone_tuple is 6
The third element of iphone_tuple is h
All odd-indexed elements of iphone_tuple are ('p', 'o', 'e')
iphone
There is p
<class 'str'>
<class 'tuple'>

If you want to change the value inside tuple,

1. Change it to list
2. Change the value of the list
3. Change back to tuple

In [ ]:
iphone_tuple_2 = ('i', 'p', 'h', 0, 'n', 'e')

# Change it to list
iphone_tuple_2 = list(iphone_tuple_2)

# Change the value of the list
iphone_tuple_2[3] = 'o'

# Change back to tuple
iphone_tuple_2 = tuple(iphone_tuple_2)

print(iphone_tuple_2)

('i', 'p', 'h', 'o', 'n', 'e')

But why do we use tuple?

1. Faster: It takes less time to search inside tuple.
2. Safer: The data inside tuple cannot be corrobated.
3. Dictionary Usage: This will be explained later on.

## Set

**Set** is similar with tuple, but it is **not ordered**.

In [ ]:
# Empty Set
companies = {}

companies = {'LG', 'Samsung', 'Foxconn'}

# Run - Runtime - Restart Runtime - Run...Can you see the difference?
print(companies)

{'Foxconn', 'Samsung', 'LG'}

So, we cannot search data inside a set

In [ ]:
print(companies[2])

TypeError: ignored

We cannot modify existing values inside the set, but we can add or delete values.

In [ ]:
# We use 'add()' instead of 'append()'
companies.add('3M')
print(companies)

companies.remove('LG')
print(companies)

{'Samsung', 'LG', 'Foxconn', '3M'}
{'Samsung', 'Foxconn', '3M'}

Set cannot have a **duplicate** data inside

In [ ]:
# How many times 'LG' appears in output?
companies = {'LG', 'Samsung', '3M', 'Foxconn', 'LG'}
print(companies)

{'Foxconn', '3M', 'Samsung', 'LG'}

In [ ]:
# Did you see these before???

print("The length of companies is", len(companies))

mixed_set = {'Samsung', 1, True}

for i in companies:
    print(i)

if 'SK' not in companies:
    print("Why not?")

The length of companies is 4
Foxconn
3M
Samsung
LG
Why not?

We can also get **intersection** and **union** when using set!

In [ ]:
companies_1 = {'AMD', 'NVIDIA', 'Intel'}
companies_2 = {'NVIDIA', 'Meta', 'Google'}

print(companies_1.union(companies_2))
print(companies_1.intersection(companies_2))

{'Meta', 'AMD', 'NVIDIA', 'Google', 'Intel'}
{'NVIDIA'}

So why do we use set?

1. We can **efficiently** remove duplicates
2. Finding union and intersection
3. Dictionary Usage: Will explain later

### 🎯 Challenge 1

There are so many errors in this code. Can you fix them?

In [ ]:
negative_words = ['no', 'not', 'bad', 'lose', 'failure']

def positivity(thing):

  # INPUT: thing -> tuple
  # OUTPUT: thing -> tuple
  # Replace all elements that imply negativity to a '^-^', then remove all repetitive words

  ### YOUR CHANGES HERE ###

  # replace all negative stuff
  for i in range(len(thing)):
    if thing[i] in negative_words:
      thing[i] = ' ^o^'

  # Remove all repetitive stuff

  return thing

  ### END OF CHANGES ###

change_me = ['happy', 'smile', 'not', 'bad', '!', 'win', 'bad', 'failure', 'smile']
positivity(change_me)

['happy', 'smile', '^o^', '^o^', '!', 'win', '^o^', '^o^', 'smile']

## Dictionary

Dictionaries are used to store data values in **key:value** pairs, just like actual dictionary.

In [ ]:
# Remember the structure of {key:value}!!

# Empty Dictionary (Same as set)
basic_information = {}

# 'Name' -> Key, 'Jaehong Lim' -> value
basic_information["Name"] = "Jaehong Lim"

# Can have multiple keys and multiple values.
basic_information = {
    "Name" : 'Jaehong Lim',
    "Age" : 22,
    "Major" : 'Computer Science',
    "Married" : False
 }

print(basic_information)

{'Name': 'Jaehong Lim', 'Age': 22, 'Major': 'Computer Science', 'Married': False}

We have to use key in order to change or add data in dictionary.

In [ ]:
# Accessing data stored in 'value' with 'key'
print(basic_information["Major"])

# Changing data stored in 'value' with 'key'
basic_information["Age"] = 21

# Adding data with new 'key' and corresponding new 'value'
basic_information["Address"] = "Seoul"

# We can change data by update() method
basic_information.update({"Address": "Champaign"})

print(basic_information)

Computer Science
{'Name': 'Jaehong Lim', 'Age': 21, 'Major': 'Computer Science', 'Married': False, 'Address': 'Champaign'}

Dictionary is **ordered**.

Dictionary **cannot** have duplicate keys.

Dictionary **can** have duplicate values.

In [ ]:
# How many times 'Year' appear? How many times 'UNFORGIVEN' apperar?
music_info = {
    'Title': 'ANTIFRAGILE',
    'Artist': 'LE SSERAFIM',
    'Album': 'UNFORGIVEN',
    'Year': 2023,
    'Year': "UNFORGIVEN"}

print(music_info)

{'Title': 'ANTIFRAGILE', 'Artist': 'LE SSERAFIM', 'Album': 'UNFORGIVEN', 'Year': 'UNFORGIVEN'}

We can use **keys()** and **values()** function to print out separate list of keys and values

In [ ]:
print(list(basic_information.keys()))
print(list(basic_information.values()))

['Name', 'Age', 'Major', 'Married', 'Address']
['Jaehong Lim', 21, 'Computer Science', False, 'Champaign']

Wait a minute... How can we use if/ for/ while with dictionary?

In [ ]:
# Can you tell the difference between these two?
for i in basic_information:
  if basic_information[i] == 22:
    print("Liar!")

for i in basic_information.keys():
  if basic_information[i] == 22:
    print("Seriously?")

In [ ]:
# To search for keys...
if "Name" in basic_information:
    print("We have name!")

We have name!

We cannot have list as a key in dictionary because its value may change. However, we can have **tuple**! Remember why?

In [ ]:
team_name = {['Hangoo', 'Jaehong'] : "Jaegoo"}

TypeError: ignored

In [ ]:
team_name = {('Hangoo', 'Jaehong') : 'Jaegoo'}

We can have list and tuple as a value.

In [ ]:
# List as value
meal_pref = {'Chinese' : ['Jaehong', 'Hangoo'], 'Japanese': ['Max, June'], 'Korean': ['Seunghwan', 'Joseph']}
meal_pref['Chinese'][0] = 'Danny'

# Tuple as value
meal_pref = {'Chinese' : ('Jaehong', 'Hangoo'), 'Japanese': ('Max, June'), 'Korean': ('Seunghwan', 'Joseph')}

print(meal_pref['Chinese'][0])

Jaehong

We can have dictionary inside of a dictionary!

In [ ]:
# Inside dictionary called 'students', we have three more separate dictionaries
students = {
    'Jaehong': {
        'Role' : 'Team Leader',
        'Major': 'Computer Science',
        'Team' : 'Python Learning'
    },

    'Hangoo': {
        'Role' : 'Vice Chairman',
        'Major': 'Computer Science',
        'Team' : 'Machine Learning'
    },

    'Hoyoung': {
        'Role' : 'Chairman',
        'Major': 'Computer Science',
        'Team' : 'Data Visualization'
    }
}

print(students['Hangoo']['Major'])

Computer Science

### 🎯 Challenge 2

This is a dictionary containing position and age of Korean football players.

For players having 'defense' positions, subtract their age by 1.

For players having 'midfield' positions, add their age by 1.

For players having 'forward' positions, multiply their age by 2.

In [ ]:
korean_football_players = {
    'Heung Min Son' : {
        "Position": "Forward",
        "Age": 31
    },

    'Min Jae Kim' : {
        "Position": "Defense",
        "Age": 26
    },

    'Kang In Lee' : {
        "Position": "Midfield",
        "Age": 22
    },

    'Hee Chan Hwang' : {
        "Position": "Forward",
        "Age": 27
    },

    'In Beom Hwang' : {
        "Position": "Midfield",
        "Age": 27
    },

    'Jae Sung Lee' : {
        "Position": "Midfield",
        "Age": 31
    },

    'Seung Woo Lee' : {
        "Position": "Midfield",
        "Age": 25
    },

    'Young Gwon Kim' : {
        "Position": "Defense",
        "Age": 33
    },

    'Gue Sung Cho' : {
        "Position": "Forward",
        "points": 25
    }
}

def position_check(korean_football_players):

  # INPUT : Korean football player information dictionary
  # OUTPUT : Korean football player information dictionary with age changed

  ### YOUR CODE HERE ###
  for i in korean_football_players:
    if korean_football_players[i]["position"] == "Defence":
      korean_football_players[i]["points"] -= 1

  ### END OF CODE ###

  return korean_football_players

position_check(korean_football_players)

KeyError: ignored

## Week 4 HW

Warm Up
$$ $$
Create a new dictionary variable named UIUC.

 The UIUC dictionary should have the following three Key-Pair values.

- Key Major should have the values ["CS", "ECE", "MATH"].
- Key Class should have the values ["CS101", "CS124","ECE110", "ECE120", "MATH241", "Math257"].
- Key Year should have the values [2024, 2025, 2026, 2027] (all int type).

McDonalds is thinking about changing their menu price.

To help our good friend, we created dictionaries containing 'mcdonalds_set_menu' and 'menu_price_change'. With these dictionaries, finish the function 'new_menu'!

In other words, use the integer inside 'menu_price_change' to have according price for each set menu in 'mcdonalds_set_menu'.

In [2]:
# YOUR CODE STARTS HERE
UIUC = {
    "Major" : ['CS','ECE','MATH'],
    "Class" : ["CS101", "CS124","ECE110", "ECE120", "MATH241", "Math257"],
    "Year" : [2024, 2025, 2026, 2027]
}
UIUC

{'Major': ['CS', 'ECE', 'MATH'],
 'Class': ['CS101', 'CS124', 'ECE110', 'ECE120', 'MATH241', 'Math257'],
 'Year': [2024, 2025, 2026, 2027]}

In [ ]:
mcdonalds_set_menu = {
    "Set A": {
        "combo": ["Burger", "Soda", "Fries"],
        # Price is in dollars
        "price" : 9.5,
    },

    "Set B": {
        "combo": ["Nuggets", "Onion Ring", "Soda"],
        "price" : 5.7
    },

    "Set C": {
        "combo": ["Ice Cream", "Soda"],
        "price" : 3.3
    },

    "Set D": {
        "combo": ["Onion Ring", "Nuggets", "Fries"],
        "price": 6.0
    },

    "Set E": {
        "combo": ["Burger", "Burger", "Ice Cream", "Ice Cream"],
        "price": 14.4
    }
}

# The integer means change in price (dollars)
menu_price_change = {
    "Burger" : -0.5,
    "Fries" : 0.9,
    "Soda" : 0.1,
    "Ice Cream": 0,
    "Nuggets": 1.3,
    "Onion Ring": -1.0
}

In [ ]:
def new_menu(set_menu, price_change):

  ### YOUR CODE HERE ###
  for i in mcdonalds_set_menu:
    print(i)
    for j in mcdonalds_set_menu[i]["combo"]:
      mcdonalds_set_menu[i]["price"] += menu_price_change[j]

  ### END OF CODE ###

  return round(set_menu["Set A"]["price"], 1), round(set_menu["Set B"]["price"], 1), round(set_menu["Set C"]["price"], 1), round(set_menu["Set D"]["price"], 1), round(set_menu["Set E"]["price"], 1)


setA, setB, setC, setD, setE = new_menu(mcdonalds_set_menu, menu_price_change)

print("Set A: ", setA)
print("Set B: ", setB)
print("Set C: ", setC)
print("Set D: ", setD)
print("Set E: ", setE)

Set A:  10.0
Set B:  6.1
Set C:  3.4
Set D:  7.2
Set E:  13.4